sudo: required

services:
  - docker

before_install:
  - docker build -t docker-complex -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true docker-complex npm test

after_success:
  - docker build -t eleach6633/multi-client -f ./client/Dockerfile ./client
  - docker build -t eleach6633/multi-nginx  -f ./nginx/Dockerfile ./nginx
  - docker build -t eleach6633/multi-server -f ./server/Dockerfile ./server
  - docker build -t eleach6633/multi-worker -f ./worker/Dockerfile ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

  - docker push eleach6633/multi-client
  - docker push eleach6633/multi-nginx
  - docker push eleach6633/multi-server
  - docker push eleach6633/multi-worker
